############################# English ############################
[en]
languageName = "En"
title = "Pengadilan Militer III-12 Surabaya"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Lokasi"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Jl. Ir. H. Juanda No.85 Sidoarjo, Jawa Timur 61254"
# copyright
copyright = "Design by [APYNX](https://aping.my.id/ "Aping Blog") with [Hugo](https://gohugo.io/ "Hugo")"



############################# Deutsch ############################
[de]
languageName = "De"
title = "Bigspring Hugo"
contentDir = "content/deutsch" # content/german
weight = 2
########### footer content ##########
footer_menu_left = "Firma"
footer_menu_middle = "Produkte"
footer_menu_right = "Support"
footer_content = "Lorem ipsum dolor sit amet, consectetur elit. Consjat tristique eget amet, tempus eu at cttur."
# copyright
copyright = "Design von [Themefisher](https://themefisher.com/) Entwickelt von [Gethugothemes](https://gethugothemes.com/)"